// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Ib2RjO8haBSPa8Oqzo29wsSMHSlzShI',
    appId: '1:19600933652:web:467b25fb515b1a169d3801',
    messagingSenderId: '19600933652',
    projectId: 'swachh-saathi',
    authDomain: 'swachh-saathi.firebaseapp.com',
    storageBucket: 'swachh-saathi.appspot.com',
    measurementId: 'G-8T5G43HLH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvQtRUaixg_EPsUVXssxgD81t16B-QCvI',
    appId: '1:19600933652:android:ef68fde232084f969d3801',
    messagingSenderId: '19600933652',
    projectId: 'swachh-saathi',
    storageBucket: 'swachh-saathi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Pnyb6LPazDWhof5AsROHxgkPKri99yQ',
    appId: '1:19600933652:ios:8449c8d021b7ad609d3801',
    messagingSenderId: '19600933652',
    projectId: 'swachh-saathi',
    storageBucket: 'swachh-saathi.appspot.com',
    iosBundleId: 'com.example.swachhSaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Pnyb6LPazDWhof5AsROHxgkPKri99yQ',
    appId: '1:19600933652:ios:8449c8d021b7ad609d3801',
    messagingSenderId: '19600933652',
    projectId: 'swachh-saathi',
    storageBucket: 'swachh-saathi.appspot.com',
    iosBundleId: 'com.example.swachhSaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Ib2RjO8haBSPa8Oqzo29wsSMHSlzShI',
    appId: '1:19600933652:web:ffe6c6fb8b31d5dc9d3801',
    messagingSenderId: '19600933652',
    projectId: 'swachh-saathi',
    authDomain: 'swachh-saathi.firebaseapp.com',
    storageBucket: 'swachh-saathi.appspot.com',
    measurementId: 'G-T0ES1MJP49',
  );
}
